name: "Test"
on:
  push:
  pull_request:
    branches: [ main ]
jobs:
  check-code:
    name: Check Code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: yarn install
    - name: Run test
      run: make test
